# Generated by Django 4.0.3 on 2022-03-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cnn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_file', models.TextField()),
                ('classifier', models.CharField(max_length=100)),
            ],
        ),
    ]
